CREATE TABLE IF NOT EXISTS "public"."games" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "game_id" bigint NOT NULL
);

ALTER TABLE "public"."games" OWNER TO "postgres";

ALTER TABLE "public"."games" ALTER COLUMN "game_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."games_game_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL
);

ALTER TABLE "public"."profiles" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."ratings" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "rating" double precision DEFAULT '1200'::bigint NOT NULL,
    "game_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "other_data" "json" DEFAULT '{}'::"json" NOT NULL,
    "type" "text" DEFAULT 'glicko'::"text" NOT NULL
);

ALTER TABLE "public"."ratings" OWNER TO "postgres";

ALTER TABLE ONLY "public"."ratings"
    ADD CONSTRAINT "elos_pkey" PRIMARY KEY ("user_id", "game_id");

ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_pkey" PRIMARY KEY ("game_id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("user_id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."ratings"
    ADD CONSTRAINT "ratings_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("game_id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."ratings"
    ADD CONSTRAINT "ratings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

CREATE POLICY "Enable insert for authenticated users only" ON "public"."games" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON "public"."games" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."ratings" FOR SELECT USING (true);

CREATE POLICY "You may only add your own rating" ON "public"."ratings" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "You may only update your own rating" ON "public"."ratings" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));

ALTER TABLE "public"."games" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."ratings" ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
  insert into public.profiles (user_id)
  values (new.id);
  return new;
end;
$$;

ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
