ALTER TABLE "public"."profiles" ADD COLUMN "display_name" text NOT NULL DEFAULT '';

CREATE TABLE "public"."tournaments" (
    "tournament_id" bigint NOT NULL,
    "game_id" bigint NOT NULL,
    "name" text NOT NULL,
    "type" text NOT NULL,
    "status" text NOT NULL DEFAULT 'pending',
    "created_by" uuid NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."tournaments" OWNER TO "postgres";

ALTER TABLE "public"."tournaments" ALTER COLUMN "tournament_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tournaments_tournament_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."tournaments"
    ADD CONSTRAINT "tournaments_pkey" PRIMARY KEY ("tournament_id");

ALTER TABLE ONLY "public"."tournaments"
    ADD CONSTRAINT "tournaments_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("game_id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."tournaments"
    ADD CONSTRAINT "tournaments_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."tournaments"
    ADD CONSTRAINT "tournaments_type_check" CHECK ("type" IN ('bracket', 'round_robin'));

ALTER TABLE ONLY "public"."tournaments"
    ADD CONSTRAINT "tournaments_status_check" CHECK ("status" IN ('pending', 'active', 'completed'));

CREATE TABLE "public"."tournament_participants" (
    "tournament_id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."tournament_participants" OWNER TO "postgres";

ALTER TABLE ONLY "public"."tournament_participants"
    ADD CONSTRAINT "tournament_participants_pkey" PRIMARY KEY ("tournament_id", "user_id");

ALTER TABLE ONLY "public"."tournament_participants"
    ADD CONSTRAINT "tournament_participants_tournament_id_fkey" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("tournament_id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."tournament_participants"
    ADD CONSTRAINT "tournament_participants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE "public"."tournaments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tournament_participants" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "public"."tournaments" FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON "public"."tournaments" FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Enable update for creator" ON "public"."tournaments" FOR UPDATE USING ("auth"."uid"() = "created_by") WITH CHECK ("auth"."uid"() = "created_by");

CREATE POLICY "Enable read access for all users" ON "public"."tournament_participants" FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON "public"."tournament_participants" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable read access for own profile" ON "public"."profiles" FOR SELECT USING (true);
CREATE POLICY "Enable update for own profile" ON "public"."profiles" FOR UPDATE USING ("auth"."uid"() = "user_id") WITH CHECK ("auth"."uid"() = "user_id");
